I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 155, in script
    $ lynda_rating -= 1
  File "game/script.rpy", line 155, in <module>
    $ lynda_rating -= 1
NameError: name 'lynda_rating' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 155, in script
    $ lynda_rating -= 1
  File "C:\Users\court\Desktop\renpy-8.3.3-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\court\Desktop\renpy-8.3.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 155, in <module>
    $ lynda_rating -= 1
NameError: name 'lynda_rating' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
Project Self 1.0
Wed Dec 11 16:33:40 2024
